version: '3'
services:
  # username: admin password: admin
  sonarqube:
    image: sonarqube:9.1.0-community
    container_name: sonarqube
    ports:
      - "9005:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres-server:5432/sonardb
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=postgrespwd
    volumes:
      - ./.docker/sonarqube/sonarqube_logs:/opt/sonarqube/logs
      - ./.docker/sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - ./.docker/sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./.docker/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - ./.docker/sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - sonarnet

  postgres-server:
    image: postgres:14.0
    container_name: postgres-server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sonar
      POSTGRES_DB: sonardb
      POSTGRES_PASSWORD: postgrespwd
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data
      - ./.docker/postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarnet
  
networks:
  sonarnet:
    driver: bridge