version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "kalilventur@gmail.com.br"
      PGADMIN_DEFAULT_PASSWORD: "cz7YkLL09@!0*"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
