version: "3"

services:
  # web vizualizer
  mongo-express:
    container_name: "mongo-express"
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: kalil
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2020!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2020!
    links:
      - mongo
    networks:
      - mongo-network

  mongo:
    container_name: "mongo-database"
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2020!
    ports:
      - "27017:27017"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
