version: "3"

services:
  #Configuration Sql Server
  mssql-database:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: mssql.database
    environment:
      ACCEPT_EULA: "Y"
      SA_USER: "sa"
      SA_PASSWORD: "cz7YkLL09@!0*"
    ports:
      - "1433:1433"
    networks:
      - mssql-compose-network

#Network for containers
networks:
  mssql-compose-network:
    driver: bridge
