# Simple docker compose for MySQL
version: "3"

services:
  #Configuration for MySQL
  database:
    image: mysql:latest
    container_name: mysql.database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # Time Zone
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: home
      MYSQL_USER: kalil
      MYSQL_PASSWORD: kalil
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

  #Configuration for Adminer
  adminer:
    image: adminer:latest
    container_name: adminer.mysql.database
    restart: always
    ports:
      - 8800:8080
    networks:
      - mysql-compose-network

#Network for communication in MySQL and Adminer
networks:
  mysql-compose-network:
    driver: bridge
