# Simple docker compose for MySQL
version: '3'

services:
#Configuration for MySQL
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: sharebook
      MYSQL_USER: kalil
      MYSQL_PASSWORD: kalil
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

#Configuration for Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

#Network for communication in MySQL and Adminer
networks: 
  mysql-compose-network:
    driver: bridge